stages:
  download_dataset:
    cmd: python scripts/download_dataset.py --dataset Bingsu/Human_Action_Recognition --output_dir data/har_dataset --version v1
    deps:
      - scripts/download_dataset.py
    outs:
      - data/har_dataset/v1:
          persist: true

  filter_dataset:
    cmd: python scripts/download_dataset.py --dataset Bingsu/Human_Action_Recognition --output_dir data/har_dataset --version v2 --split train
    deps:
      - scripts/download_dataset.py
    outs:
      - data/har_dataset/v2:
          persist: true
    frozen: true  # Only run when explicitly requested

  prepare_data:
    cmd: python -c "from data.preprocessing import prepare_har_dataset; from transformers import CLIPTokenizerFast, CLIPImageProcessor; tokenizer = CLIPTokenizerFast.from_pretrained('openai/clip-vit-base-patch16'); image_processor = CLIPImageProcessor.from_pretrained('openai/clip-vit-base-patch16'); prepare_har_dataset(tokenizer, image_processor, val_ratio=0.15, test_ratio=0.25, seed=42)"
    deps:
      - data/har_dataset/v1
    frozen: true  # Only run when explicitly requested

  train:
    cmd: python train.py --distributed_mode none --batch_size 128 --max_epochs 15 --lr 3e-6 --output_dir outputs/model_run
    deps:
      - train.py
      - data/har_dataset/v1
    outs:
      - outputs/model_run:
          persist: true
    frozen: true  # Only run when explicitly requested

  evaluate:
    cmd: python evaluate.py --model_path outputs/model_run/best_model.pt --output_dir outputs/evaluation
    deps:
      - evaluate.py
      - outputs/model_run
    outs:
      - outputs/evaluation:
          persist: true
    frozen: true  # Only run when explicitly requested

  export:
    cmd: python -m CLIP_HAR_PROJECT.deployment.export_clip_model
      --model_path models/clip_har/model.pt
      --config_path configs/training_config.yaml
      --export_format all
      --output_dir exports
    deps:
      - CLIP_HAR_PROJECT/deployment/export_clip_model.py
      - models/clip_har/model.pt
    outs:
      - exports/model.onnx
      - exports/model.trt:
          persist: true
